CREATE DATABASE DB_POWERBI;

CREATE TABLE CLIENTES(
    id SERIAL PRIMARY KEY,
    nome TEXT,
    sobrenome TEXT,
    email TEXT
);

INSERT INTO CLIENTES (NOME, SOBRENOME, EMAIL) VALUES('João','Silva','joao@example.com');
INSERT INTO CLIENTES (NOME, SOBRENOME, EMAIL) VALUES ('Maria','Santos','maria@example.com');
INSERT INTO CLIENTES (NOME, SOBRENOME, EMAIL) VALUES ('Pedro','Souza','pedro@example.com');

SELECT * FROM CLIENTES;

CREATE TABLE PEDIDOS(
    id SERIAL PRIMARY KEY,
    id_cliente INT,
    data_pedido DATE,
    total NUMERIC(6,2),
    status_pedidos TEXT CHECK(STATUS_PEDIDOS IN ('EM ANDAMENTO','FINALIZADO', 'CANCELADO')),
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID)
);

ALTER TABLE PEDIDOS 
    ALTER COLUMN STATUS_PEDIDOS
        SET DEFAULT 'EM ANDAMENTO';


INSERT INTO PEDIDOS (ID_CLIENTE, DATA_PEDIDO, TOTAL, STATUS_PEDIDOS)
    VALUES (1, '2024-04-01', 50.00, 'FINALIZADO');

INSERT INTO PEDIDOS (ID_CLIENTE, DATA_PEDIDO, TOTAL, STATUS_PEDIDOS)
    VALUES (2, '2024-04-02', 75.00, 'EM ANDAMENTO');

INSERT INTO PEDIDOS (ID_CLIENTE, DATA_PEDIDO, TOTAL, STATUS_PEDIDOS)
    VALUES (1, '2024-04-03', 120.00, 'FINALIZADO');

INSERT INTO PEDIDOS (ID_CLIENTE, DATA_PEDIDO, TOTAL, STATUS_PEDIDOS)
    VALUES (3, '2024-04-04', 35.00, 'CANCELADO');

INSERT INTO PEDIDOS (ID_CLIENTE, DATA_PEDIDO, TOTAL, STATUS_PEDIDOS)
    VALUES (3, '2024-04-05', 90.00, 'EM ANDAMENTO');

INSERT INTO PEDIDOS (ID_CLIENTE, DATA_PEDIDO, TOTAL, STATUS_PEDIDOS)
    VALUES (2, '2024-04-06', 95.00, 'CANCELADO');

SELECT * FROM PEDIDOS;